server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8

spring:
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}
  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jwt:
    secret: ZmNfYXB0bmVyX3Byb2plY3Rfand0X3NlY3JldF9rZXlfdmFsdWVfYmFzZV82NF9lbmNvZGluZw==

logging:
  level:
    '[org.springframework.boot.web]': INFO

#s3
cloud:
  aws:
    credentials:
      access-key: ${aws.credentials.access.key}
      secret-key: ${aws.credentials.secret.key}
    s3:
      bucket: ${aws.s3.bucket}
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
    '[org.springframework.boot.web]':

aws:
  kms:
    key: 69ee4900-f7d9-4c99-9ac8-224f0210f16d