spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tentendb
    username: admin
    password: root
  servlet:
    multipart:
      max-file-size: 20MB

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      '[hibernate.format_sql]': true
