server:
  port: 8084

spring:
  config:
    activate:
      on-profile: dev

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aptnerdb.cnwyomomod4o.ap-northeast-2.rds.amazonaws.com:3306/aptnerdb?allowPublicKeyRetrieval=true&useSSL=false
    username: aptner
    password: aptner88
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: AQICAHj6muJJAtkMOAc19YL0GOR+Z2UZhi6f04vzv88m4Hk2OQHQmDUR2U3LFcedEVwexzdhAAAA5zCB5AYJKoZIhvcNAQcGoIHWMIHTAgEAMIHNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGSkGZcb/u56mlI+5AIBEICBnyzNPvr3qDRY0Jwy7laOFSDk5zpPyzOPT2aTkCXpwPcE/5XjvhL9ktgQmMiDtpCrqkIl9xTCsGlzqmUYCdPYBeRERXKPLdU3V8r/9MJxYIxxMyr5QpLXdQiDFFm5l6WdGsRND+sG2+85T8pbAzsw//XtitkaDHZk1jHFuAmMQYmKraLy2fuH9lJf6H0WS3i+MmMSpoN9/qPLqibArcak/w==
  #    username: AQICAHj6muJJAtkMOAc19YL0GOR+Z2UZhi6f04vzv88m4Hk2OQHdthuRqCvGhSB3d5QuWXjTAAAAZDBiBgkqhkiG9w0BBwagVTBTAgEAME4GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM7Uu3/tF83p1C8upqAgEQgCEJXx0jlKyvpv5veoKoDvU1Ptg1MWM4NhvyEWbZVurAUyw=
  #    password: AQICAHj6muJJAtkMOAc19YL0GOR+Z2UZhi6f04vzv88m4Hk2OQEOxNkR3i7jly8SKsZuLeWkAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMi+N6O8/Gwb4l7uLrAgEQgCOMf3A6M1E09MYjGPCh94ud4SFQduBq14WkTOL0PFUjTaE8BQ==

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
        show-sql: true

  jwt:
    secret: ZmNfYXB0bmVyX3Byb2plY3Rfand0X3NlY3JldF9rZXlfdmFsdWVfYmFzZV82NF9lbmNvZGluZw==

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.fc8.application
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false

aws:
  kms:
    key: 69ee4900-f7d9-4c99-9ac8-224f0210f16d6

cloud:
  aws:
    credentials:
      access-key: "AKIA2UC27JBWVEPIKZOE"
      secret-key: "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"
    s3:
      bucket: "elasticbeanstalk-ap-northeast-2-730335234157"
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

coolsms:
  api:
    key: "NCSAOMLQWYGJXBO3"
    secret: "WZVNJDNKGUD8CU5C1T7BPUPR47YFPFVD"