server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aptnerdb.cnwyomomod4o.ap-northeast-2.rds.amazonaws.com:3306/aptnerdb?allowPublicKeyRetrieval=true&useSSL=false
    username: aptner
    password: aptner88

  servlet:
    multipart:
      max-file-size: 20MB

  jwt:
    secret: "ZmNfYXB0bmVyX3Byb2plY3Rfand0X3NlY3JldF9rZXlfdmFsdWVfYmFzZV82NF9lbmNvZGluZw=="

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
        show-sql: true

logging:
  level:
    '[org.springframework.boot.web]': DEBUG

#s3
cloud:
  aws:
    credentials:
      access-key: "AKIA2UC27JBWVEPIKZOE"
      secret-key: "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"
    s3:
      bucket: "elasticbeanstalk-ap-northeast-2-730335234157"
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

coolsms:
  api:
    key: "NCSAOMLQWYGJXBO3"
    secret: "WZVNJDNKGUD8CU5C1T7BPUPR47YFPFVD"

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.fc8.application
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false

aws:
  kms:
    key: 69ee4900-f7d9-4c99-9ac8-224f0210f16d6



---

spring:
  config:
    activate:
      on-profile: ci
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aptnerdb
    username: aptner
    password: aptner88
  servlet:
    multipart:
      max-file-size: 20MB

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
        show-sql: true

---

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aptnerdb.cnwyomomod4o.ap-northeast-2.rds.amazonaws.com:3306/aptnerdb?allowPublicKeyRetrieval=true&useSSL=false
    username: aptner
    password: aptner88

  servlet:
    multipart:
      max-file-size: 20MB

  jwt:
    secret: "ZmNfYXB0bmVyX3Byb2plY3Rfand0X3NlY3JldF9rZXlfdmFsdWVfYmFzZV82NF9lbmNvZGluZw=="

  data:
    redis:
      host: aptnerredis.3rf4kd.ng.0001.apn2.cache.amazonaws.com
      port: 6379

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력
        show-sql: true

logging:
  level:
    '[org.springframework.boot.web]': DEBUG

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  packages-to-scan: com.fc8.application
  swagger-ui:
    tags-sorter: alpha
    groups-order: asc
    syntax-highlight:
      activated: true
    try-it-out-enabled: false
  enable-kotlin: false


#s3
cloud:
  aws:
    credentials:
      access-key: "AKIA2UC27JBWVEPIKZOE"
      secret-key: "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"
    s3:
      bucket: "elasticbeanstalk-ap-northeast-2-730335234157"
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'

coolsms:
  api:
    key: "NCSAOMLQWYGJXBO3"
    secret: "WZVNJDNKGUD8CU5C1T7BPUPR47YFPFVD"